wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
    t:
      1:
      - 1
      - 3
      2:
      - 1
      - 3
      4: 3.7.6
      5: 0.10.17
end_epoch:
  desc: null
  value: 5000
joblib_batch_size:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.0001
model_path:
  desc: null
  value: null
normalize:
  desc: null
  value: false
obs_len:
  desc: null
  value: 20
pred_len:
  desc: null
  value: 30
test:
  desc: null
  value: false
test_batch_size:
  desc: null
  value: 1
test_features:
  desc: null
  value: Traj/forecasting_features_test.pkl
train_batch_size:
  desc: null
  value: 512
train_features:
  desc: null
  value: Traj/forecasting_features_train.pkl
traj_save_path:
  desc: null
  value: null
use_delta:
  desc: null
  value: true
use_map:
  desc: null
  value: false
use_social:
  desc: null
  value: false
val_batch_size:
  desc: null
  value: 512
val_features:
  desc: null
  value: Traj/forecasting_features_val.pkl
wandb:
  desc: null
  value: true
